export const CHANNELS = {
  authBegin: "auth:begin",
  authLogout: "auth:logout",
  authOpenActivation: "auth:open-activation",
  authSnapshot: "auth:snapshot",
  catalogFollowed: "catalog:followed",
  catalogFollowedChannels: "catalog:followed-channels",
  catalogLive: "catalog:live",
  catalogSearch: "catalog:search",
  catalogTopCategories: "catalog:top-categories",
  catalogVideos: "catalog:videos",
  chatInputBegin: "chat-input:begin",
  chatInputEnd: "chat-input:end",
  chatInputEscape: "chat-input:escape",
  favouritesAdd: "favourites:add",
  favouritesList: "favourites:list",
  favouritesRemove: "favourites:remove",
  playbackProgressGet: "playback-progress:get",
  playbackProgressList: "playback-progress:list",
  playbackProgressRemove: "playback-progress:remove",
  playbackProgressSave: "playback-progress:save",
  settingsSaveClientId: "settings:save-client-id",
  settingsSnapshot: "settings:snapshot",
  systemActivateEmbeddedPlayer: "system:activate-embedded-player",
  systemIsSteamGameMode: "system:is-steam-game-mode",
  systemRestoreShellFullscreen: "system:restore-shell-fullscreen",
  systemToggleFullscreen: "system:toggle-fullscreen",
} as const
